name: Node CI

on:
  - push
  - pull_request

env:
   CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
          node-version: ${{ matrix.node-version }}
    - name: npm install
        # Install project
      run: |
        make install
    - name: Run linter
        # Run Linter
      run: |
        make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.alexey }}
        with:
          coverageCommand: make test-coverage
          debug: true
          
