name: jest-test
on: 
  - push
  
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: npm install
        run: 
          npm install
      - name: Run jest
        run: 
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true