name: jest-test
on: 
  - push
  
jobs:
  build:
    runs-on: ubuntu-18.04
 
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: npm install
        run: 
          make install
      - name: Run jest
        run: 
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 04ea4638b0405eb2a75b69b5585343d8e48b2cab8b382f5ccc0cc79d916777af
        with:
          coverageCommand: make test-coverage
          debug: true
          