name: jest-test
on: 
  - push
  
jobs:
  build:
    runs-on: ubuntu-18.04
 
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: npm install
        run: 
          make install
      - name: Run jest
        run: 
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: <c6881c80cc3e83eef288e3951875a19281b54d1bddd6175927e71134f3f1e9b0>
        with:
          coverageCommand: make test-coverage
          debug: true
          